services:

  code-server:
    container_name: ${CODE_SERVER_LABEL}
    image: ${CODE_SERVER_IMAGE}
    restart: unless-stopped
    env_file: .env
    ports:
      - ${CODE_SERVER_PORT}:${CODE_SERVER_PORT}
    volumes:
      - ${CONFIG}/${CODE_SERVER_LABEL}:/config
      - ${BACKUP}/${CODE_SERVER_LABEL}/config.yaml:/config/.config/${CODE_SERVER_LABEL}/config.yaml
      - ${NAS}:/nas
    labels:
      - homepage.group=${GROUP_NAME}
      - homepage.weight=${CODE_SERVER_WEIGHT}
      - homepage.name=${CODE_SERVER_PRETTY_LABEL}
      - homepage.icon=${CODE_SERVER_ICON}
      - homepage.href=${CODE_SERVER_HTTP}
      - homepage.siteMonitor=${CODE_SERVER_HTTP}

  trilium:
    container_name: ${TRILIUM_LABEL}
    image: ${TRILIUM_IMAGE}
    restart: unless-stopped
    env_file: .env
    ports:
      - ${TRILIUM_PORT}:${TRILIUM_PORT}
    volumes:
      - ${TIME_ZONE}:${TIME_ZONE}:ro
      - ${CONFIG}/${TRILIUM_LABEL}:/home/node/trilium-data
      - ${BACKUP}/${TRILIUM_LABEL}/backup:/home/node/trilium-data/backup
      - ${BACKUP}/${TRILIUM_LABEL}/config.ini:/home/node/trilium-data/config.ini
    labels:
      - homepage.group=${GROUP_NAME}
      - homepage.weight=${TRILIUM_WEIGHT}
      - homepage.name=${TRILIUM_PRETTY_LABEL}
      - homepage.icon=${TRILIUM_ICON}
      - homepage.href=${TRILIUM_HTTP}
      - homepage.siteMonitor=${TRILIUM_HTTP}

  unms:
    container_name: ${UNMS_LABEL}
    image: ${UNMS_IMAGE}
    restart: unless-stopped
    env_file: .env
    hostname: tools
    extra_hosts:
      - "tools:127.0.0.1"
    ports:
      - ${UNMS_WEB_PORT}:${UNMS_WEB_PORT}
      - ${UNMS_WEB_PORT_S}:${UNMS_WEB_PORT_S}
      - ${UNMS_PORT}:${UNMS_PORT}/udp
    volumes:
      - ${TIME_ZONE}:${TIME_ZONE}
      - /${CONFIG}/${UNMS_LABEL}:/config
      - /${BACKUP}/${UNMS_LABEL}/config-backups:/config/unms/config-backups
      - /${BACKUP}/${UNMS_LABEL}/unms-backups:/config/unms/unms-backups
    labels:
      - homepage.group=${GROUP_NAME}
      - homepage.weight=${UNMS_WEIGHT}
      - homepage.name=${UNMS_LABEL}
      - homepage.icon=${UNMS_ICON}
      - homepage.href=${UNMS_HTTP}
      - homepage.siteMonitor=${UNMS_HTTP}
    environment:
      - PUID=10000