[webcam ArtemisCam]
enabled: True
service: webrtc-go2rtc
snapshot_url: https://go2rtc.matthewshannon.art/api/frame.jpeg?src=artemis
stream_url: https://go2rtc.matthewshannon.art/stream.html?src=artemis&mode=webrtc

[wled chamber]
type: http
address: 192.168.0.134 # Artemis
initial_red: 0.5
initial_green: 0.4
initial_blue: 0.3
chain_count: 26