[webcam ArtemisCam]
enabled: True
service: webrtc-go2rtc
snapshot_url: https://go2rtc.matthewshannon.art/api/frame.jpeg?src=artemis
stream_url: https://go2rtc.matthewshannon.art/stream.html?src=artemis&mode=webrtc