[webcam ArtemisCam]
enabled: True
service: webrtc-go2rtc
snapshot_url: https://go2rtc.matthewshannon.art/api/frame.jpeg?src=artemis
stream_url: https://go2rtc.matthewshannon.art/stream.html?src=artemis&mode=webrtc

[wled chamber]
type: http
address: wled-artemis
chain_count: 26

[update_manager happy-hare]
type: git_repo
path: ~/Happy-Hare
origin: https://github.com/moggieuk/Happy-Hare.git
primary_branch: main
install_script: install.sh
managed_services: klipper

[mmu_server]
enable_file_preprocessor: True
enable_toolchange_next_pos: True
update_spoolman_location: True
