[webcam CharlieCam]
enabled: True
service: webrtc-go2rtc
snapshot_url: https://go2rtc.matthewshannon.art/api/frame.jpeg?src=charlie
stream_url: https://go2rtc.matthewshannon.art/stream.html?src=charlie&mode=webrtc