[webcam DennisCam]
enabled: True
service: webrtc-go2rtc
snapshot_url: https://go2rtc.matthewshannon.art/api/frame.jpeg?src=dennis
stream_url: https://go2rtc.matthewshannon.art/stream.html?src=dennis&mode=webrtc