[webcam c110Dennis]
enabled: True
service: mjpegstreamer
target_fps: 15
target_fps_idle: 5
stream_url: https://c110dennis.matthewshannon.art/mjpeg
snapshot_url: https://c110dennis.matthewshannon.art/image.jpg

[wled chamber]
type: http
address: wled-dennis # Dennis
chain_count: 26